from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="greek_scraper",
    version="0.9.4",
    author="Charis Nikolaidis",
    author_email="ncharis97@gmail.com",
    description="Ultra-fast and efficient web scraper with GPU utilization for text cleaning and JSON output. Supports generic and language-specific scraping.",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/Charisn/Greek-web-scraper",

    project_urls={
        "Bug Tracker": "https://github.com/Charisn/Greek-web-scraper/issues",
        "Documentation": "https://github.com/Charisn/Greek-web-scraper#readme",
        "Source": "https://github.com/Charisn/Greek-web-scraper",
    },

    packages=find_packages(),
    install_requires=[
        "scrapy",
        "cupy-cuda12x",
        "trafilatura",
        "tldextract",
        "beautifulsoup4",
        "chardet",
        "numpy",
        "Twisted",
        "itemadapter",
        "itemloaders",
        "parsel",
        "w3lib",
        "queuelib",
        "lxml",
        "cssselect",
        "PyDispatcher",
        "zope.interface",
        "cryptography",
        "pyOpenSSL",
        "service-identity",
        "idna",
        "requests",
        "urllib3",
        "attrs",
        "cffi",
        "pycparser",
        "certifi",
        "charset-normalizer",
        "frozenlist",
        "aiosignal",
        "hyperlink",
        "incremental",
        "automat",
        "constantly",
        "six",
        "babel",
        "pytz",
        "python-dateutil",
    ],
    extras_require={
        "dev": [
            "pytest",
            "flake8",
            "black",
            "isort",
        ],
    },

    keywords="web scraping gpu scraper text-cleaning json scraping",
    python_requires='>=3.10',
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Topic :: Internet :: WWW/HTTP :: Indexing/Search",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Environment :: GPU",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],

)